### ISSUE TITLE
Feature request: apply Color Calibration automatically

### ISSUE THREAD

**Issue by fabiosirna** [UliGesing/Darktable-Initial-Workflow-Module#21]
Hi thanks for this script, I'm wondering if it will be possible to apply automatically the color calibration.
The equivalent of hitting this button and set the white balance from the image area:

![image](https://github.com/user-attachments/assets/41781cbc-375d-4f04-803d-60c98b089195)

**Comment by UliGesing** [comment]
Hello, thanks for the friendly message. I'll be away for the next few days, so I'll take a look at it then. I think the feature is feasible. Best regards, Uli.

**Comment by UliGesing** [comment]
Hello, there is a new release: https://github.com/UliGesing/Darktable-Initial-Workflow-Module/releases

It contains "your" new option for color calibration module: set white balance to detected from area

You need dt4.9 / 5.0 to use it.

Hope, it works for you :-)
