### ISSUE TITLE
?Bad results!

### ISSUE THREAD

**Issue by megvadulthangya** [UliGesing/Darktable-Initial-Workflow-Module#23]
Hi Guyz!
I can use photoshop, capture one, Exposure7, Luminar Neo, easily ... 
But i tryed [Darktable in docker](https://hub.docker.com/r/linuxserver/darktable)... Then i search for darktable workflow scripts then i ended up here...
i installed git in the docker container, then installed this Darktable-Initial-Workflow-Module thingy thing... 
I just selected all of my pictures from the Lightable --- or how its called, then go to initial workflow script thingy and just push run... All the default settings, im not changed anything, on anywhere... 
I did nothing else and the results are junk. Waste of time. And space on hard disks.
If this is the current state of photo editing in open source that is so sad.

"[Would you look at this? Just Look At It!](https://github.com/megvadulthangya/Darktable-Initial-Workflow-Module_results/blob/main/README.md)" 

Almost all just goes white balance way off O.o but see yourself

Am i doing smthing wrong?
I dont understand what is this script is for? Or what?

**Comment by UliGesing** [comment]
Hello. There are two projects here, the extensive darktable and the small script as a supplement. You can use the script to automate some of the first steps in developing your raw files. The standard settings are suitable for some photos, but certainly not all; they form a basis. For further processing, you should be familiar with darktable and its modules. Tutorials on YouTube are a good place to start.

The white balance you mentioned is set using algorithms in darktable. There are several options and presets in the "color calibration" module. The ideal value depends heavily on the photo and in particular on the photographer's intention. So there is no perfect solution for all types of photos.

If you like the operation and results of the software products you mentioned better, you should use them.

If you are ready to get to know darktable more intensively, darktable is a powerful tool that often offers you more options for influence.
